{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mattshoe",
    "module": "shoebox-data",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "shoebox-data-0.0.2.aar",
          "url": "shoebox-data-0.0.2.aar",
          "size": 138435,
          "sha512": "5359742be2b2a1fe3c1114ad5829dca155da50cc46239baacf805eb49b3970be11b0c308d98da8614dad93867f440fe13c24a0bc904da896ed0750217ee8cf14",
          "sha256": "cdc5e5481d2267f6196f2715185603e13d31c75b37b35fc70fbc7d5224f600a0",
          "sha1": "a89d7dd16c8713a14ef586560675f1bb1325fbe2",
          "md5": "3559048d5c7e3f06148884b36eb1e8e2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "shoebox-data-0.0.2.aar",
          "url": "shoebox-data-0.0.2.aar",
          "size": 138435,
          "sha512": "5359742be2b2a1fe3c1114ad5829dca155da50cc46239baacf805eb49b3970be11b0c308d98da8614dad93867f440fe13c24a0bc904da896ed0750217ee8cf14",
          "sha256": "cdc5e5481d2267f6196f2715185603e13d31c75b37b35fc70fbc7d5224f600a0",
          "sha1": "a89d7dd16c8713a14ef586560675f1bb1325fbe2",
          "md5": "3559048d5c7e3f06148884b36eb1e8e2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "shoebox-data-0.0.2-sources.jar",
          "url": "shoebox-data-0.0.2-sources.jar",
          "size": 33103,
          "sha512": "19791475cdf144d1433d64988fec3408556ab1be4baea6e4e11e44cb68e639e7be04a6c52507df035e4be8cb648c037b82ec68a18d09a1afa2833a353be7f1a1",
          "sha256": "50acaa086f3a169b2a21a8a8ae30c9c57ac186e231fef71a9bcfa69febc28975",
          "sha1": "62df181b4e4a9d8763f96808f21ced51786b34a2",
          "md5": "8d89a39e77b6d49c3e70366e0a807791"
        }
      ]
    }
  ]
}
